### ISSUE TITLE
Multiple Error when trying to Run.

### ISSUE THREAD

**Issue by ashwarhussain** [Ruturaj123/Flowchart-Detection#6]
I was trying to run your code for Flowchart detection from https://github.com/Ruturaj123/Flowchart-Detection. I am hit my multiple errors. 

first in Object .py files in object_detection\utils folder uses protos and core folder files and Import was giving me errors. Temporarily I have copied Protos and core folders inside Utils folder to avoid that. 

then I had an error that object_detection\Inference_graph\frozen_inference_graph.pb cannot be created. I have manually created this file to avoid error.

now I am getting an error  "KeyError: "The name 'image_tensor:0' refers to a Tensor which does not exist. The operation, 'image_tensor', does not exist in the graph.""

Can you please help me out here.

final error message:
(base) C:\Code\Machine Learning\MyWizard\GTR\Flowchart-Detection-master\Flowchart-Detection-master>python Object_detection_image.py
2019-08-21 18:30:50.362623: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "Object_detection_image.py", line 124, in <module>
    flowchart_detector.detect()
  File "Object_detection_image.py", line 54, in detect
    image_tensor = self.detection_graph.get_tensor_by_name('image_tensor:0')
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3654, in get_tensor_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3478, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3520, in _as_graph_element_locked
    "graph." % (repr(name), repr(op_name)))
KeyError: "The name 'image_tensor:0' refers to a Tensor which does not exist. The operation, 'image_tensor', does not exist in the graph."

**Comment by Ruturaj123** [comment]
Hi @ashwarhussain ,
So for the first error that you mentioned, it might be because you are running it on windows and I had added the path which follows linux format (i.e. `/` instead of `\` in the path). So maybe resolving that would solve the issue.
Regarding the second and third error, they are linked and are mostly because of the frozen file. Maybe it needs to be compiled again using the object detection API.

**Comment by ashwarhussain** [comment]
Thanks for your response @Ruturaj123 ...

I am a newbie in tensor Flow and Deep learning .. can you please help me with instruction on how to recompile using Object Detection API please.

regards,
Ashwar.

**Comment by ashwarhussain** [comment]
@Ruturaj123 
when you say compile again do you mean "“C:\Program Files\protoc-3.4.0-win32\bin\protoc.exe” object_detection/protos/*.proto --python_out=." ? then even after doing this I am getting the same error of Inference_graph.

**Comment by ashwarhussain** [comment]
was doing some reading and I think the PB file gets created in the training exercise. 
python export_inference_graph.py --input_type image_tensor --pipeline_config_path training/faster_rcnn_inception_v2_pets.config --trained_checkpoint_prefix training/model.ckpt-XXXX --output_directory inference_graph ..
I think Inference_Graph folder is missing in your solution ..
